feat(playground): set-up playground component
ionic-team/ionic-docs pull request #2188
Opened 2022-02-08 22:29 UTC by sean-perkins

Introduces the new `<Playground />` component for documenting Ionic Framework components in the docs site.

Displays the initial design with partial dark-mode support.

Split from #2185

2022-02-18 19:58 UTC, liamdebeasi commented on src/components/global/Playground/index.tsx
> +                'playground__control-button ' + (mode === Mode.iOS ? 'playground__control-button--selected' : '')
Can we move this logic to above the return function? Same thing with line 33. Similar to how we do https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/datetime/datetime.tsx#L1590-L1592

2022-02-18 20:26 UTC, sean-perkins commented on src/components/global/Playground/playground.css
> +/* Hides the horizontal scrollbar when the toolbar has horizontal overflow */
I think we can remove this for now. Originally when prototyping, on smaller viewports the controls would crowd and the height of the scrollbar was visually overflowing the top bar's inner contents. If that problem returns, we can track a bug and work with Ben.

2022-02-18 20:30 UTC, sean-perkins commented on src/components/global/Playground/playground.css
> +  grid-template-columns: repeat(4, auto);
Originally, just because I knew that flex box had mixed support for `gap`. But it looks like that isn't the case anymore.

2022-02-18 20:32 UTC, liamdebeasi requested changes

2022-02-18 20:32 UTC, liamdebeasi commented on src/components/global/Playground/playground.css
> +   * @prop --playground-btn-color The text color of the button in the toolbar.
Can we document all of the variables?

2022-02-18 21:01 UTC, sean-perkins commented on src/components/global/Playground/playground.css
> +  /* Only render the separator between sections when there is an accompanying section */
I can rework the comment 👍 

This selector is used to create the vertical divider between groups of controls in the toolbar. You will notice in the Figma design, there is no divider after the "iOS/MD" group.

2022-02-21 14:56 UTC, amandaesmith3 requested changes
Had a few minor nitpicks, nothing too crazy :eyes;

2022-02-21 14:56 UTC, amandaesmith3 commented on src/components/global/Playground/index.tsx
> +          {/* TODO FW:-742: Code language switcher */}
```suggestion
          {/* TODO FW-742: Code language switcher */}
```

2022-02-21 14:56 UTC, amandaesmith3 commented on src/components/global/Playground/playground.css
> +.playground {
Can we move the variable documentation into one block, similar to how the components do it? Would be a bit easier to read.

2022-02-21 14:56 UTC, amandaesmith3 commented on src/components/global/Playground/playground.css
> +  overflow-y: auto;
Should this be `overflow-x`? Feels weird to have a toolbar scroll vertically.

2022-02-21 16:53 UTC, amandaesmith3 approved these changes

2022-02-23 20:35 UTC, liamdebeasi approved these changes

2022-02-23 20:51 UTC, merged