Update ios.md
ionic-team/ionic-docs pull request #2202
Opened 2022-02-23 16:07 UTC by Webrow

Following these steps cause an error where the podsfile has not been created nor installed. after copy ios, capacitor update is required to setup the podsfile and native dependencies.

2022-02-28 20:36 UTC, sean-perkins requested changes

2022-02-28 20:36 UTC, sean-perkins commented on docs/developing/ios.md
> +   $ ionic capactior update
```suggestion
   $ ionic capacitor update
```

Typo for CLI command.

2022-02-28 20:50 UTC, sean-perkins approved these changes

2022-09-19 20:54 UTC, merged

2022-09-19 20:54 UTC, brandyscarney commented
Thanks for the PR!