feat(virtual-scroll): usage with custom scroll target
ionic-team/ionic-docs pull request #2229
Opened 2022-03-15 15:36 UTC by sean-perkins

Updates the sections for note regarding Ionic components to include the usage instructions for the custom scroll target.

2022-03-15 18:16 UTC, amandaesmith3 requested changes

2022-03-15 18:16 UTC, amandaesmith3 commented on docs/react/virtual-scroll.md
> +    <Virtuoso className="ion-content-scroll-host">// Your existing content and configurations</Virtuoso>
```suggestion
    <Virtuoso className="ion-content-scroll-host">
      {/* Your existing content and configurations */}
    </Virtuoso>
```

2022-03-16 15:17 UTC, liamdebeasi requested changes

2022-03-16 15:17 UTC, liamdebeasi commented on docs/angular/virtual-scroll.md
> +<ion-content scroll-y="false">
Now that we are in an Angular specific documentation, we should use the angular syntax here. So `scroll-y` should be `[scrollY]`.

2022-03-16 20:31 UTC, amandaesmith3 approved these changes

2022-03-18 13:40 UTC, liamdebeasi approved these changes
Good to merge once my comment below is addressed.

2022-03-18 13:40 UTC, liamdebeasi commented on docs/react/virtual-scroll.md
> +<IonPage>
React has `<IonPage>`, but Vue does not. Can we either remove it from React or add it to Vue?

2022-04-08 13:55 UTC, lincolnthree commented
Hi all. Please see the following issue in the Angular CDK, as I believe this will make much of this easier if we can get these features merged: https://github.com/angular/components/pull/24394

2022-04-08 14:58 UTC, sean-perkins commented
@lincolnthree that feature change would allow developers to make use of the `ion-content`'s scroll container instead of the virtual scroll container, but the implementation code may be more difficult for implementers to follow:

```html
<ion-content #content>
  <cdk-virtual-scroll-viewport [scrollableElement]="content.getScrollElement() | async">
    ...
 </cdk-virtual-scroll-viewport>
</ion-content>
```

I don't see any downsides to that feature change, but we would continue to offer this class approach to support all virtual scrolling solutions in all supported frameworks, not just CDK & Angular.

For example, this is how it looks for React, Vue and Angular with the same implementation pattern: https://gist.github.com/sean-perkins/277524ef0e450591907a87acec15af11

Appreciate your feedback and making us aware of that feature/change from Angular!

2022-04-08 15:47 UTC, merged

2022-08-17 22:03 UTC, Albert-Gao commented
with this being merged, i guess this doc is outdated? https://ionicframework.com/docs/react/virtual-scroll#a-note-on-ionic-components :)

2023-02-18 20:24 UTC, avalanche1 commented
@sean-perkins pls deprecate  https://ionicframework.com/docs/react/virtual-scroll#a-note-on-ionic-components as obsolete

2023-02-20 14:31 UTC, liamdebeasi commented
Thanks everyone, I fixed this in https://github.com/ionic-team/ionic-docs/pull/2780.