docs(datetime): add button playgrounds
ionic-team/ionic-docs pull request #2301
Opened 2022-04-28 19:22 UTC by liamdebeasi

This PR adds the following playgrounds:

1. Showing default confirmation buttons.
2. Customizing default confirmation button texts.
3. Slotting in custom confirmation buttons.

These fall under the "Buttons" category.

2022-05-02 16:58 UTC, sean-perkins requested changes

2022-05-02 16:58 UTC, sean-perkins commented on static/usage/datetime/buttons/customizing-buttons/javascript.md
> +  const datetime = document.querySelector('ion-datetime');
```suggestion
  var datetime = document.querySelector('ion-datetime');
```

Stackblitz limitation... if you click any of the buttons in your live example you will get an exception. For whatever reason they don't allow `const` or `let` at the document scope.

2022-05-02 17:51 UTC, amandaejohnston commented on docs/api/datetime.md
>  ## Buttons
I'm not seeing the footer/buttons on any of the datetimes when in `md` mode, although they do show in the Stackblitz so I assume they're supposed to be there 🤔

2022-05-02 18:48 UTC, amandaejohnston approved these changes

2022-05-03 15:34 UTC, sean-perkins approved these changes
Good to merge once merge conflicts are resolved.

2022-05-03 15:42 UTC, merged