docs(picker): component playground examples
ionic-team/ionic-docs pull request #2309
Opened 2022-05-02 16:12 UTC by sean-perkins

Introduces component playground examples for `ion-picker` for the single and multi-column examples.

2022-05-02 18:36 UTC, amandaejohnston approved these changes

2022-05-02 18:48 UTC, liamdebeasi requested changes
Some of the examples have `class="ion-padding"`  on `ion-content` (such as `multiple-column/react.md`) and some do not (such as `multiple-column/vue.md`). Can we make this consistent across all the examples?

2022-05-02 18:48 UTC, liamdebeasi commented on static/usage/picker/multiple-column/angular/app_component_ts.md
> +          handler: (value) => {},
Should there be something in here to illustrate what you can do with the handler?

2022-05-02 18:48 UTC, liamdebeasi commented on static/usage/picker/multiple-column/javascript.md
> +  <ion-content fullscreen>
While this technically works, `fullscreen` isn't an attribute on `ion-content`. We should have it say `fullscreen="true"`.

2022-05-02 18:48 UTC, liamdebeasi commented on static/usage/picker/multiple-column/vue.md
> +  <ion-content fullscreen>
```suggestion
  <ion-content :fullscreen="true">
```

2022-05-02 18:48 UTC, liamdebeasi commented on static/usage/picker/multiple-column/javascript.md
> +  <ion-content fullscreen>
Actually do we even need to use fullscreen in any of these samples?

2022-05-03 15:28 UTC, sean-perkins commented on static/usage/picker/single-column/javascript.md
> +    <div class="container">
Ahh you are right, this was from copy/paste. I'll clean-up, good catch!

2022-05-03 15:33 UTC, merged