docs(modal): playground set-up
ionic-team/ionic-docs pull request #2312
Opened 2022-05-03 15:27 UTC by sean-perkins

This PR is the base PR that all other playground modal examples will be merged into, before this branch is finally merged back into `component-playground`. 

This PR:
- Removes the Usage section
- Removes the existing demos
- Adds new sections for the playground examples
- Adds new text/content for those individual sections (worth reading through to make sure I did not miss anything). 

The text/content changes are mainly for presenting and dismissing sections. I am still working on the other sections and will introduce any text/content changes as part of those separate PRs.

2022-05-03 18:55 UTC, amandaejohnston requested changes

2022-05-03 18:55 UTC, amandaejohnston commented on docs/api/modal.md
> +#### Basic
This header isn't needed since it's the only one at this level.

2022-05-03 18:55 UTC, amandaejohnston commented on docs/api/modal.md
>  ## Interfaces
This isn't strictly relevant, but it's exacerbated by the removal of the Usage section -- I noticed that there are two Interfaces sections, with slightly different content. 🤔 We should probably consolidate them here.

2022-05-03 19:01 UTC, liamdebeasi approved these changes

2022-05-24 19:55 UTC, amandaejohnston approved these changes

2022-05-24 19:56 UTC, merged