docs(modal): controller playground
ionic-team/ionic-docs pull request #2322
Opened 2022-05-04 03:14 UTC by sean-perkins

Re-approach to the controller modal component playground example.

This PR is in favor of: #2315 and #2319.

2022-05-05 14:41 UTC, amandaejohnston commented on static/usage/modal/controller/vue/example_vue.md
> +          this.message = `Hello, ${data}`;
```suggestion
          this.message = `Hello, ${data}!`;
```
Very minor, but the inconsistency would bother me 😆

2022-05-05 15:56 UTC, amandaejohnston approved these changes

2022-05-09 19:30 UTC, liamdebeasi requested changes

2022-05-09 19:30 UTC, liamdebeasi commented on static/usage/modal/controller/react.md
> +      <IonContent>
```suggestion
      <IonContent class="ion-padding">
```

2022-05-16 20:19 UTC, merged