docs(modal): card playground
ionic-team/ionic-docs pull request #2324
Opened 2022-05-04 19:57 UTC by sean-perkins

Introduces the card style playground for `ion-modal`.

Decided to remove the full screen section (already cover heavily in the inline and controller examples) and the sizes section (changing modal height can be covered in the styling section).

2022-05-05 15:13 UTC, amandaejohnston requested changes

2022-05-05 15:13 UTC, amandaejohnston commented on docs/api/modal.md
> +<CardExample />
On the JS Stackblitz, if I click the Close button (rather than swiping to close) I get an error (`modal is not defined`).

2022-05-05 15:54 UTC, amandaejohnston approved these changes

2022-05-09 19:36 UTC, liamdebeasi reviewed
Also same comments as https://github.com/ionic-team/ionic-docs/pull/2323#pullrequestreview-966736895

2022-05-09 19:36 UTC, liamdebeasi commented on static/usage/modal/card/basic/react.md
> +            '--backdrop-opacity': '0.2',
Why do we set the backdrop opacity?

2022-05-17 14:44 UTC, liamdebeasi approved these changes
Looks good. I saw a few other issues, but they do not appear to be caused by changes in this PR.

I created FW-1524 and FW-1525 to track these.

2022-05-17 15:29 UTC, merged