docs(modal): modal styling playground
ionic-team/ionic-docs pull request #2326
Opened 2022-05-05 19:48 UTC by sean-perkins

Introduces component playground examples for styling and custom animations for `ion-modal`. 

Updated the Angular Stackblitz base example, so it always includes an `app.component.css`. This allows us to have examples that customize `app.component.html` and `app.component.css`, but don't need to include an `app.component.ts` in the code snippet section, as we aren't making any changes to it.

2022-05-06 14:55 UTC, amandaejohnston requested changes

2022-05-06 14:55 UTC, amandaejohnston commented on docs/api/modal.md
> +<AnimationsExample />
There's an error when opening the Angular Stackblitz (`Property 'modal' does not exist on type 'AppComponent'`).

2022-05-06 15:51 UTC, amandaejohnston approved these changes

2022-05-16 02:41 UTC, sean-perkins commented on static/usage/modal/styling/animations/javascript/index_ts.md
> +(window as any).createAnimation = createAnimation;
The HTML example imports the stylesheets directly in the template:
```html
<link rel="stylesheet" type="text/css" href="https://cdn.skypack.dev/@ionic/core/css/core.css" />
<link rel="stylesheet" type="text/css" href="https://cdn.skypack.dev/@ionic/core/css/ionic.bundle.css" />
```

2022-05-16 14:59 UTC, liamdebeasi approved these changes

2022-05-20 16:12 UTC, merged