docs(playground): add remaining basic usage
ionic-team/ionic-docs pull request #2367
Opened 2022-06-06 14:12 UTC by liamdebeasi

Adds the following playgrounds:

- Programmatically toggling accordions
- Listening for ionChange
- Showing multiple accordions at a time

2022-06-07 15:31 UTC, amandaejohnston requested changes

2022-06-07 15:31 UTC, amandaejohnston commented on static/usage/accordion/toggle/javascript.md
> +  const toggleAccordion = () => {
```suggestion
  var toggleAccordion = () => {
```
Currently you get a `toggleAccordion is not defined` error when clicking the button in Stackblitz.

2022-06-07 15:31 UTC, amandaejohnston commented on static/usage/accordion/multiple/react.md
> +      <IonAccordionGroup multiple={true} value={['first', 'third']}>
This is running into this issue: https://github.com/ionic-team/ionic-framework/issues/25041 You may want to set the value via JS instead as a workaround.

2022-06-08 15:03 UTC, amandaejohnston approved these changes

2022-06-13 17:43 UTC, sean-perkins requested changes

2022-06-13 17:47 UTC, liamdebeasi commented on static/usage/accordion/listen-changes/angular-ts.md
> +  accordionGroupChange = (ev: any) => {
There is, but I ran into this issue: https://github.com/ionic-team/ionic-framework/issues/24245

2022-06-13 17:51 UTC, sean-perkins commented on static/usage/accordion/listen-changes/angular-ts.md
> +  accordionGroupChange = (ev: any) => {
Ok, figured 👍 I ran into the same, debated on having `(ionEvent)="any$(onEvent($event)"` or just type casting any. I think this is good for now. I believe Stencil has merged the upstream fix that was our blocker to getting this bug resolved.

2022-06-13 17:51 UTC, sean-perkins approved these changes

2022-06-13 17:53 UTC, merged