docs(alert): add buttons playground
ionic-team/ionic-docs pull request #2423
Opened 2022-06-24 20:10 UTC by amandaejohnston

2022-06-27 18:50 UTC, sean-perkins requested changes

2022-06-27 19:15 UTC, liamdebeasi requested changes

2022-06-27 19:15 UTC, liamdebeasi commented on static/usage/alert/buttons/javascript.md
> +  button.addEventListener('click', presentAlert);
```suggestion
```

Can we use an `onclick` handler instead?

2022-06-28 21:10 UTC, liamdebeasi approved these changes

2022-06-30 16:49 UTC, sean-perkins approved these changes

2022-06-30 16:49 UTC, sean-perkins commented on static/usage/alert/buttons/angular/angular_ts.md
> +  handlerMessage = "";
~ Minor nitpick, this and `roleMessage` could be using single quotes instead of double quotes.

2022-07-01 17:48 UTC, merged