docs(alert): add customization playground
ionic-team/ionic-docs pull request #2428
Opened 2022-06-27 18:46 UTC by amandaejohnston

Adds the Customization playground and removes a couple of dead anchor links from the docs.

2022-06-27 19:04 UTC, sean-perkins commented on static/usage/alert/customization/angular/angular_ts.md
> +  constructor(public alertController: AlertController) {}
```suggestion
  constructor(private alertController: AlertController) {}
```

2022-06-27 19:06 UTC, sean-perkins commented on docs/api/alert.md
> +### Example
If this example is focused around styling, can we update this heading to be "Theming" or "Styling"?

2022-06-28 21:20 UTC, liamdebeasi requested changes
Can we make this playground look a bit more "real world"? For example, Chakra UI has a nice sample here: https://chakra-ui.com/docs/components/alert-dialog/usage.

Optional: It might be valuable to keep the theming consistent. For example, Tailwind's samples all have consistent themes with coordinated colors: https://tailwindcss.com/ (in the "Build whatever you want, seriously." section)

2022-06-29 18:27 UTC, amandaejohnston commented
Good point! Changed to use the `success` colors instead 👍

2022-06-30 16:52 UTC, sean-perkins commented
![Screen Shot 2022-06-30 at 12 50 38 PM](https://user-images.githubusercontent.com/13732623/176733814-059e6834-0a4a-41b4-bf28-e22f3b68dd08.png)

The iOS preview could still use some refinement. The cancel button is clipping and the confirm button border radius does not match consistently.

2022-06-30 17:18 UTC, amandaejohnston commented
Ah, that'd be from the buttons wrapping; your screen size is likely a bit smaller than mine. I'll just make it a simple yes/no to avoid that.

2022-07-01 17:44 UTC, sean-perkins approved these changes
Alert looks great now 👍

2022-07-01 17:48 UTC, merged