docs(grid): add components playgrounds
ionic-team/ionic-docs pull request #2596
Opened 2022-10-05 22:22 UTC by brandyscarney

This PR adds the following component playgrounds:

- Basic Usage
- Fixed Grid
- Column Size
  - Content-based size
  - Specified size
  - Responsive size
- Column Offset
  - Specified offset
  - Responsive offset
- Column Push & Pull
  - Specified push & pull
  - Responsive push & pull
- Alignment
  - Vertical Alignment
  - Horizontal Alignment
- Customizing the Grid
  - Fixed Width
  - Number of Columns
  - Padding

It updates the column & row API documentation to point to the grid API documentation.

It also removes the grid documentation from layout here: https://ionicframework.com/docs/layout/grid

2022-10-07 19:18 UTC, amandaejohnston requested changes
Love your examples, everything looks really snazzy 🎉

2022-10-11 15:00 UTC, brandyscarney commented on docs/layout/grid.md
> -title: Responsive Grid
Good call! Added a PR to redirect here: https://github.com/ionic-team/ionic-nginx/pull/20

2022-10-11 15:01 UTC, brandyscarney commented
@liamdebeasi @sean-perkins Are you both okay with getting rid of the file https://ionicframework.com/docs/layout/grid completely and redirecting to the api grid documentation?

2022-10-11 15:16 UTC, amandaejohnston approved these changes

2022-10-11 15:16 UTC, liamdebeasi commented
Agree on getting rid of the docs page in favor of the Grid component. We should not break the URL though, so a 301 redirect to the component page is an option here.

2022-10-11 16:25 UTC, brandyscarney commented
@liamdebeasi Yeah there is a redirect added here: https://github.com/ionic-team/ionic-nginx/pull/20

@sean-perkins Added it back to the sidebar but it directs to `api/grid` here: https://github.com/ionic-team/ionic-docs/pull/2596/files#diff-9a6a0fdafefb0eecffb77784bc94f5ad984062167b8bcb7c4a899c90f6f567e8R33

Can be seen here: https://ionic-docs-git-fw-1292-ionic1.vercel.app/docs/

Let me know if you want any other changes!

2022-10-14 22:14 UTC, sean-perkins approved these changes

2022-10-17 13:21 UTC, merged