docs(ripple-effect): add component playgrounds
ionic-team/ionic-docs pull request #2608
Opened 2022-10-11 22:00 UTC by brandyscarney

2022-10-13 14:15 UTC, amandaejohnston requested changes

2022-10-13 15:41 UTC, brandyscarney commented on static/usage/ripple-effect/basic/demo.html
> +    }
Added a wrapper and passed that, let me know what you think!

2022-10-13 17:07 UTC, amandaejohnston approved these changes
Looks great to me now, thank you!

2022-10-14 19:21 UTC, sean-perkins approved these changes

2022-10-14 21:27 UTC, merged