docs(angular): config provider usage and content updates
ionic-team/ionic-docs pull request #2614
Opened 2022-10-18 21:33 UTC by sean-perkins

Revamps the documentation surrounding the `Config` provider and usage in Angular. If we agree with the general layout and content adjustments, I can make similar changes to React and Vue.

Related issues: #2580

2022-10-19 15:03 UTC, brandyscarney requested changes
I'm not crazy about the formatting for the API reference & Interface, but the content additions look good to me.

2022-10-19 15:40 UTC, sean-perkins commented on docs/angular/config.md
> +Ionic Config is not reactive. It is recommended to use a component's properties or a directive when you want to override its default behavior.
I agree this is confusing. I updated the content/example. Let me know if that helps or if there is additional changes required.

2022-10-19 16:31 UTC, brandyscarney commented
Dropping a link to an API reference Ben sent in Slack for future reference: https://mui.com/material-ui/customization/theming/#api

2022-10-19 16:37 UTC, brandyscarney commented on docs/angular/config.md
> +Ionic Config is not reactive. It is recommended to use a component's properties or a directive when you want to override its default behavior.
It's definitely easier to understand now, especially with the full code example for the backButtonText. 👍

2022-10-19 16:56 UTC, brandyscarney approved these changes

2022-10-19 16:56 UTC, brandyscarney commented on docs/angular/config.md
> +Below is the config options that Ionic uses.
```suggestion
Below are the config options that Ionic uses.
```

2022-10-20 15:06 UTC, amandaejohnston approved these changes

2022-10-21 17:12 UTC, merged