docs(refresher): add component playgrounds
ionic-team/ionic-docs pull request #2617
Opened 2022-10-19 17:06 UTC by brandyscarney

2022-10-19 18:18 UTC, brandyscarney commented
I removed the unused imports, added a description for advanced usage and moved it to the bottom. Let me know if you see any issues!

2022-10-24 15:33 UTC, sean-perkins approved these changes
Looks good to me 👍

2022-10-25 14:15 UTC, amandaejohnston requested changes
I think you really nailed it with the code balance 👍 Just had a couple content-related comments.

2022-10-25 15:28 UTC, amandaejohnston approved these changes

2022-10-25 16:00 UTC, merged