docs(infinite-scroll): playground examples
ionic-team/ionic-docs pull request #2625
Opened 2022-10-27 18:10 UTC by sean-perkins

Introduces component playground examples for:
- Basic usage
- Using properties on `ion-infinite-scroll-content`
- Using custom content for the infinite scroll content

Updates the `ion-infinite-scroll-content` docs to link the usage on `ion-infinite-scroll`. 

Opted against adding playgrounds for the virtual scroll usage and for the accessibility section.
- Virtual scroll usage should really be shown with a virtual scroll library. We should consider adding support to the component playground to specify dependencies per example (will need to investigate how package-lock files effect this).
- The accessibility section doesn't have different code for the different frameworks, so showing a code snippet is the clearest way to articulate the usage.

2022-10-27 18:14 UTC, sean-perkins commented
Should we consider any additional examples for `threshold`, `position`, etc.?

2022-10-28 17:05 UTC, amandaejohnston requested changes
I'm good without any additional playgrounds; I'd say the prop descriptions are self-explanatory.

2022-11-02 21:18 UTC, sean-perkins commented on docs/api/infinite-scroll.md
> +<Basic />
I ended up just bumping all of them to 50. Depending on the resolution of your monitor, 30 will still be too short.

2022-11-09 16:47 UTC, amandaejohnston approved these changes
I'm currently seeing broken images for the avatars: https://i.gyazo.com/1823777f74c89ee86088127d870e57d8.png Not sure if it's something on my end? Everything LGTM otherwise.

2022-11-09 18:22 UTC, liamdebeasi requested changes

2022-11-09 19:25 UTC, sean-perkins commented on static/usage/infinite-scroll/custom-infinite-scroll-content/react/main_tsx.md
> +  IonInfiniteScrollContent,
Good catch, this was just from cloning the folder for a new example. This example has a custom UI for the content, so it doesn't use the `ion-infinite-scroll-content` component.

2022-11-09 19:39 UTC, sean-perkins commented
Working through some of the last warning tweaks, will re-ping for reviews once those are available.

2022-11-14 14:54 UTC, liamdebeasi approved these changes

2022-11-14 15:31 UTC, merged