docs(buttons): add component playgrounds
ionic-team/ionic-docs pull request #2629
Opened 2022-10-28 21:42 UTC by brandyscarney

2022-10-31 15:02 UTC, liamdebeasi reviewed
I'm noticing that the ellipsis icon in "Types of Buttons" is horizontal in Angular/Vanilla JS and vertical in Vue/React despite the mode being the same.

2022-11-01 15:18 UTC, amandaejohnston requested changes

2022-11-01 15:18 UTC, amandaejohnston commented on docs/api/buttons.md
> +<CollapsibleLargeTitleButtons />
Yeah, I think "Button" would be better here for the text; "Click Me" implies something should happen when you click it.

2022-11-01 20:32 UTC, amandaejohnston approved these changes

2022-11-01 21:05 UTC, brandyscarney commented
After investigation, the issue @liamdebeasi found where switching between the ellipsis icons was not working in React & Vue was found to be a bug. I created the following framework issue for this: https://github.com/ionic-team/ionic-framework/issues/26207

2022-11-02 20:17 UTC, liamdebeasi approved these changes

2022-11-03 14:52 UTC, merged