fix(styles): add sidebar indentation for nested sections
ionic-team/ionic-docs pull request #2886
Opened 2023-04-06 15:42 UTC by sean-perkins

Updates the indentation for nested categories in the sidebar and the margin spacing between sections. 

You can see an example of a nested sidebar 3 levels deep with these same changes in this PR: https://github.com/ionic-team/ionic-docs/pull/2861.

Our goal is to maintain the spacing and indentation for the first-level categories, but allow the nested categories to be indented.

2023-04-06 22:05 UTC, jaredcbaum requested changes
<img width="204" alt="Screenshot 2023-04-06 at 4 02 49 PM" src="https://user-images.githubusercontent.com/61951482/230502270-0768671b-0392-4c6d-8110-6366807e9f3d.png">

I think we'll still want margin at the end of top level categories to conform to the design.

2023-04-07 16:36 UTC, sean-perkins commented
@jaredcbaum good catch! I moved the styles down after this:

```css
&:not(:first-child) {
  margin-block-start: 0;
}
```

This should re-introduce the spacing between sections (and at the bottom of the last section).

2023-04-10 14:43 UTC, jaredcbaum commented
<img width="300" alt="Screenshot 2023-04-10 at 8 42 32 AM" src="https://user-images.githubusercontent.com/61951482/230924191-8ddbf655-730e-4586-ad02-f24cd56255a7.png">

This still maintains the spacing when the items are collapsed. Not sure if you intended it to be this way, but figured I'd point it out just in case.

2023-04-10 15:52 UTC, sean-perkins commented
Ok third time may be the charm. I see why we were targeting the inner list for padding vs. margins between the top-level categories. 

Here is a preview against the other PR to show 3 levels deep:

![CleanShot 2023-04-10 at 11 51 34](https://user-images.githubusercontent.com/13732623/230939566-19ff4b8e-0c09-4a54-b7fe-774681363f72.png)

2023-04-10 17:47 UTC, jaredcbaum approved these changes
Looks great!

2023-04-10 18:00 UTC, merged