docs(pwa): update firebase instructions for deploying pwa
ionic-team/ionic-docs pull request #2916
Opened 2023-04-14 15:13 UTC by sean-perkins

Updates the instructions for using Firebase to deploy a PWA.

Angular: https://ionic-docs-git-docs-update-react-pwa-ionic1.vercel.app/docs/angular/pwa#deploying
React: https://ionic-docs-git-docs-update-react-pwa-ionic1.vercel.app/docs/react/pwa#deploying
Vue: https://ionic-docs-git-docs-update-react-pwa-ionic1.vercel.app/docs/vue/pwa#deploying

Co-authored-by credit has been applied from this PR: https://github.com/ionic-team/ionic-docs/pull/2708.

Note: This is from a community PR, applied to the other similar guides.

2023-04-14 16:28 UTC, thetaPC requested changes
I noticed that there was inconsistencies that some questions have quotes while other don't. Is that coming from the Firebase CLI?

2023-04-14 16:28 UTC, thetaPC commented on docs/angular/pwa.md
> +**Set up automatic builds and deploys with github?** Enter "Yes".
Change `github` to `GitHub` for consistency.

2023-04-14 16:28 UTC, thetaPC commented on docs/react/pwa.md
> +**Set up automatic builds and deploys with github?** Enter "Yes".
Change `github` to `GitHub` for consistency.

2023-04-14 16:28 UTC, thetaPC commented on docs/vue/pwa.md
> +**Set up automatic builds and deploys with github?** Enter "Yes".
Change `github` to `GitHub` for consistency.

2023-04-17 02:22 UTC, sean-perkins commented
The questions with quotes are when the CLI provides an option for selection. Otherwise we specify the manual input that the user needs to provide (branch name, project name, etc.). 

I'm open to ideas on how to better format this. I mainly kept what already existed in the docs and added the new information from the community PR.

2023-04-17 15:16 UTC, thetaPC requested changes

2023-04-17 15:16 UTC, thetaPC commented on docs/angular/pwa.md
> +**Set up automatic builds and deploys with github?** Enter "Yes".
It seems that this `github` got missed. It should be `Github`.

2023-04-17 15:17 UTC, thetaPC commented
> The questions with quotes are when the CLI provides an option for selection. Otherwise we specify the manual input that the user needs to provide (branch name, project name, etc.).
> 
> I'm open to ideas on how to better format this. I mainly kept what already existed in the docs and added the new information from the community PR.

Since it's from the CLI, then let's leave it as is. It would reduce the potential confusion by keeping it exactly the same.

2023-04-17 23:07 UTC, thetaPC approved these changes
LGTM

2023-04-20 15:16 UTC, merged