3532 docs
ionic-team/ionic-docs pull request #2971
Opened 2023-05-24 14:05 UTC by liamdebeasi

2023-05-24 16:52 UTC, thetaPC commented on docs/api/select.md
> +## Labels
Yes, let's keep it consistent. As a dev, I usually look for the same topics in the same areas. So if `labels` is known to be above `label placement` then I expect that all components would follow it. This makes it easy for when I scan docs.

2023-05-24 17:01 UTC, thetaPC requested changes

2023-05-25 13:56 UTC, liamdebeasi commented on static/usage/v7/select/label-slot/demo.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core@7.0.7-dev.11684935803.1436320b/css/ionic.bundle.css" />
I added the dev version so reviewers could test the demo, so I will remove it once the PR is approved/before it merges.

2023-05-25 15:16 UTC, amandaejohnston approved these changes

2023-05-25 17:02 UTC, merged