docs(input): add label slot and no visible label demos
ionic-team/ionic-docs pull request #2997
Opened 2023-06-14 19:14 UTC by liamdebeasi

Playgrounds for https://github.com/ionic-team/ionic-framework/pull/27650

Docs are modeled after the IonSelect label docs.

Note: I added a dev build to the label slot HTML file so reviewers can see the code in action. However, I will remove it before merging.

Preview: https://ionic-docs-git-4135-docs-ionic1.vercel.app/docs/api/input#labels

2023-06-15 17:18 UTC, brandyscarney requested changes

2023-06-15 18:32 UTC, liamdebeasi commented on docs/api/input.md
> +- `aria-label`: used for selects with no visible label
Fixed for input, select, and range in https://github.com/ionic-team/ionic-docs/pull/2997/commits/2cd03f11ba7f8735395b64c92609dc9892bf5ecd

2023-06-15 18:32 UTC, liamdebeasi commented on docs/api/input.md
> +Input has several options for supplying a label for the component:
Fixed for input, select, and range in https://github.com/ionic-team/ionic-docs/pull/2997/commits/cd40556fbe075c759e53801293e37461d674182f

2023-06-15 19:29 UTC, brandyscarney commented on static/usage/v7/input/label-slot/react.md
> +        <IonInput labelPlacement="floating" value="hi@ionic.io">
Oh weird that it works for the other frameworks though

2023-06-16 18:05 UTC, amandaejohnston approved these changes

2023-06-20 13:22 UTC, merged