docs(theming): add section about safe area padding
ionic-team/ionic-docs pull request #3065
Opened 2023-07-31 18:09 UTC by amandaejohnston

2023-07-31 18:27 UTC, liamdebeasi requested changes

2023-07-31 18:27 UTC, liamdebeasi commented on docs/theming/advanced.md
> +To accommodate this, Ionic automatically adds padding to certain components. For example, an `ion-header` component placed in an `ion-modal` will receive padding according to the top edge of the devi
Nit: We apply the safe area to the first toolbar inside the header, not the header itself

2023-07-31 18:45 UTC, brandyscarney commented
Great description! Is it possible to crop out the background behind the device? It is a little jarring in dark mode:

<img width="720" alt="Screenshot 2023-07-31 at 2 45 15 PM" src="https://github.com/ionic-team/ionic-docs/assets/6577830/1a999b7f-b020-46b0-bad4-2178d03c57ed">

2023-08-01 13:02 UTC, liamdebeasi approved these changes

2023-08-01 15:54 UTC, amandaejohnston commented
@brandyscarney Good call, I trimmed it out 👍 I left the modal padding screenshot alone since I think the white background looks okay there, but LMK if you'd like that removed too.

2023-08-01 16:03 UTC, brandyscarney approved these changes
I think the modal one is fine! This looks really good now. 👍

2023-08-01 17:06 UTC, merged