docs(modal): modifying dismiss behavior in child components
ionic-team/ionic-docs pull request #3117
Opened 2023-09-12 18:24 UTC by sean-perkins

These playground examples demonstrate how a developer can customize the `canDismiss` behavior of a parent component, when they abstract the inner template to a child component. 

These examples do not include a plain javascript example, as this is an architectural constraint geared towards frameworks.

2023-09-12 21:36 UTC, mapsandapps requested changes
Looks good other than a typo

2023-09-12 21:36 UTC, mapsandapps commented on static/usage/v7/modal/can-dismiss/child-state/angular/example_component_html.md
> +      (willPresent)="onWilPresent()"
```suggestion
      (willPresent)="onWillPresent()"
```

2023-09-13 15:34 UTC, sean-perkins commented on static/usage/v7/modal/can-dismiss/child-state/angular/example_component_html.md
> +      (willPresent)="onWilPresent()"
Oof - thanks for catching that!

2023-09-13 15:58 UTC, mapsandapps approved these changes

2023-09-18 15:31 UTC, merged