docs: show how to account for this
ionic-team/ionic-docs pull request #3334
Opened 2023-12-18 20:21 UTC by liamdebeasi

This is the same as https://github.com/ionic-team/ionic-docs/pull/3333, but targets the Ionic 8 docs.

2023-12-18 21:36 UTC, thetaPC requested changes

2023-12-18 21:36 UTC, thetaPC commented on docs/troubleshooting/runtime.md
> +See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this for more information on how `this` works in JavaScript.
```suggestion
See its [MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) for more information on how `this` works in JavaScript.
```
Web accessibility calls for natural inline links.

2023-12-18 21:36 UTC, thetaPC commented on versioned_docs/version-v7/troubleshooting/runtime.md
> +See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this for more information on how `this` works in JavaScript.
```suggestion
See its [MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) for more information on how `this` works in JavaScript.
```
Web accessibility calls for natural inline links.

2023-12-19 16:01 UTC, thetaPC approved these changes
LGTM

2023-12-19 19:03 UTC, amandaejohnston approved these changes

2023-12-19 19:03 UTC, amandaejohnston commented on docs/troubleshooting/runtime.md
> +The first way to bind `this` is to use the `bind()` method on a function instance. If a developer wanted to pass a callback called `counterFormatterFn`, then they would write `counterFormatterFn.bind
```suggestion
Certain components, such as [counterFormatter on ion-input](../api/input#counterformatter) and [pinFormatter on ion-range](../api/input#pinformatter), allow developers to pass callbacks. It's important that you bind the correct `this` value if you plan to access `this` from within the context of the callback. You may need to access `this` when using Angular components or when using class components in React. There are two ways to bind `this`:

The first way to bind `this` is to use the `bind()` method on a function instance. If you want to pass a callback called `counterFormatterFn`, then you would write `counterFormatterFn.bind(this)`.
```
Optional, but the rest of this page uses second person, so this makes it more consistent.

2023-12-19 19:03 UTC, amandaejohnston commented on versioned_docs/version-v7/troubleshooting/runtime.md
> +The first way to bind `this` is to use the `bind()` method on a function instance. If a developer wanted to pass a callback called `counterFormatterFn`, then they would write `counterFormatterFn.bind
```suggestion
Certain components, such as [counterFormatter on ion-input](../api/input#counterformatter) and [pinFormatter on ion-range](../api/input#pinformatter), allow developers to pass callbacks. It's important that you bind the correct `this` value if you plan to access `this` from within the context of the callback. You may need to access `this` when using Angular components or when using class components in React. There are two ways to bind `this`:

The first way to bind `this` is to use the `bind()` method on a function instance. If you want to pass a callback called `counterFormatterFn`, then you would write `counterFormatterFn.bind(this)`.
```

2023-12-19 22:22 UTC, merged