feat(light-mode): update styles to use new colors
ionic-team/ionic-docs pull request #3374
Opened 2024-01-08 20:44 UTC by thetaPC

2024-01-09 16:18 UTC, mapsandapps requested changes
looks good other than a couple small things

2024-01-09 16:18 UTC, mapsandapps commented on src/components/page/theming/ColorAccordion/styles.module.css
>    --ion-color-tertiary: #5260ff;
It looks like tertiary needs to change here https://ionic-docs-git-fw-5628-ionic1.vercel.app/docs/theming/basics

2024-01-09 16:18 UTC, mapsandapps commented on static/code/stackblitz/v7/react/variables.css
> +  --ion-color-primary-tint: #1a65eb;
nitpick but this whitespace is bothering me 😄

2024-01-09 16:18 UTC, mapsandapps commented on versioned_docs/version-v7/theming/advanced.md
>  | `$background-tint`  | <CodeColor color="#4c8dff">#4c8dff</CodeColor> |
tint & shade should be adjusted too, i think, using the `mix` functions above this:

```suggestion
| `$background`       | <CodeColor color="#0054e9">#0054e9</CodeColor> |
| `$background-shade` | <CodeColor color="#004acd">#004acd</CodeColor> |
| `$background-tint`  | <CodeColor color="#1a65eb">#1a65eb </CodeColor> |
```

2024-01-09 18:42 UTC, thetaPC commented on docs/react/adding-ionic-react-to-an-existing-react-project.md
>    --ion-color-secondary-rgb: 12, 209, 232;
I didn't change them based on two reasons:
1. The others aren't using the [old hex colors](https://github.com/ionic-team/ionic-framework-design-documents/blob/main/projects/ionic-framework/accessibility/theme-colors/index.md#light-theme) stated in the design doc.
2. This part of code seems to be show how a user can change the variables to make their app more unique. I suspect that this is the reason that some of the hexes aren't using the old values.

2024-01-09 20:23 UTC, thetaPC commented on docs/react/adding-ionic-react-to-an-existing-react-project.md
>    --ion-color-secondary-rgb: 12, 209, 232;
Spoke to Sean, it's been decided to reference the default values instead of having another instance of the variables.

2024-01-09 20:29 UTC, thetaPC commented on docs/react/adding-ionic-react-to-an-existing-react-project.md
>    --ion-color-secondary-rgb: 12, 209, 232;
Added in https://github.com/ionic-team/ionic-docs/pull/3374/commits/774bbb482ec53caae06897b77e7a7bd9e9109637

2024-01-09 21:22 UTC, thetaPC commented
@mapsandapps reverted the changes from the Stackblitz files since those will be done in a separate PR.

2024-01-09 23:02 UTC, thetaPC commented on docs/react/adding-ionic-react-to-an-existing-react-project.md
>    --ion-color-secondary-rgb: 12, 209, 232;
What about this? https://github.com/ionic-team/ionic-docs/pull/3374/commits/d03c4071ace91f7ea0fdd759f1aee20a34a3e0b4

2024-01-10 15:17 UTC, mapsandapps commented on docs/react/adding-ionic-react-to-an-existing-react-project.md
>    --ion-color-secondary-rgb: 12, 209, 232;
nice 😎

2024-01-10 15:17 UTC, mapsandapps approved these changes
looks good, thanks!!

2024-01-10 16:24 UTC, merged