chore(mdx): use mdx instead within docs/api
ionic-team/ionic-docs pull request #3455
Opened 2024-02-15 19:58 UTC by thetaPC

Issue URL: N/A

## What is the current behavior?

Some files are using the `.md` extension. Docusaurus v3 has [stated](https://docusaurus.io/docs/migration/v3#using-the-mdx-extension) that at some point that these files will no longer be parsed as expected and will parsed as CommonMark. They advice to use `.mdx` instead.

## What is the new behavior?

- `docs/api/` files have been switched from `.md` to `.mdx`

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

[Angular docs](https://ionic-docs-git-mdx-pt-1-ionic1.vercel.app/docs/angular/overview)
[React docs](https://ionic-docs-git-mdx-pt-1-ionic1.vercel.app/docs/react)
[Vue docs](https://ionic-docs-git-mdx-pt-1-ionic1.vercel.app/docs/vue/overview)

2024-02-15 22:36 UTC, thetaPC commented on docs/api/buttons.mdx
> +{/* Reuse the playground from the Title directory */}
Switched to the proper syntax for MDX.

2024-02-15 22:37 UTC, thetaPC commented on docs/api/grid.mdx
> +The grid is a powerful mobile-first flexbox system for building custom layouts. It is composed of three units — a grid, [row(s)](row) and [column(s)](col). Columns will expand to fill the row, and wi
Updated paths to no longer reference `.md`

2024-02-27 17:20 UTC, mapsandapps requested changes
All the changes here look good, but I did have some questions. If these are in another PR or something, lmk:

probably relevant to this PR:
* docusaurus.config.js: change lines 42-43 from .md to .mdx? (i didn't look into what this is used for; maybe we need to match both .md and .mdx and return .mdx?)
* `_templates/README.md`: line 24

also, the links in these to /api/foo.md seem to work, but maybe they should be changed for consistency?
* cross-platform.md
* structure.md
* css-shadow-parts.md
* css.variables.md
* 4-0.md

probably not relevant to this PR, but is there a plan to change these things to mdx?
* package.json: use mdx in `npm run spellcheck` command
* .editorconfig: use mdx instead of md (might need no/different rules for mdx, i didn't look into it)
* CONTRIBUTING.md: change filenames
* other lines in the docusaurus.config.js

(i marked request changes, but there may not actually be any changes needed, just let me know what's up 😄)

2024-03-28 20:40 UTC, thetaPC commented
@mapsandapps in regards to the last part in your comment: I plan to do that in a separate PR.

2024-03-29 13:22 UTC, mapsandapps approved these changes
Thanks!

2024-03-29 15:36 UTC, merged